In [1]:
import pandas as pd

# Load Dataset
df = pd.read_csv("student_preprocessing_dataset.csv")

# Display first 5 rows
df.head()

,student_id,student_name,age,sex,embarked,study_hours,total_marks,result
0,101,Aarav Sharma,19.0,female,Hyderabad,5,72,Pass
1,102,Ananya Reddy,20.0,female,Vijayawada,7,88,Pass
2,103,Arjun Kumar,NaN,male,Hyderabad,3,38,Fail
3,104,Diya Patel,18.0,female,Visakhapatnam,6,81,Pass
4,105,Rohan Singh,21.0,male,Vijayawada,4,55,Pass

In [2]:
df.shape

(32, 8)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   student_id    32 non-null     int64
 1   student_name  32 non-null     object
 2   age           28 non-null     float64
 3   sex           32 non-null     object
 4   embarked      32 non-null     object
 5   study_hours   32 non-null     int64
 6   total_marks   32 non-null     int64
 7   result        32 non-null     object
dtypes: float64(1), int64(3), object(4)
memory usage: 2.1+ KB

In [4]:
df.describe()

       student_id        age  study_hours  total_marks
count   32.000000  28.000000    32.000000     32.00000
mean   115.250000  20.035714     5.437500     68.18750
std      8.728892   1.527092     2.213412     21.39104
min    101.000000  18.000000     2.000000     29.00000
25%    107.750000  19.000000     4.000000     54.25000
50%    115.500000  20.000000     5.500000     73.00000
75%    122.250000  21.000000     7.000000     87.25000
max    130.000000  23.000000     9.000000     96.00000

In [5]:
df.isnull().sum()

student_id      0
student_name    0
age             4
sex             0
embarked        0
study_hours     0
total_marks     0
result          0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(2)

In [7]:
df['age'].fillna(
    df['age'].median(),
    inplace=True
)

C:\Users\kotha\AppData\Local\Temp\ipykernel_19920\2758770120.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(

In [8]:
df.isnull().sum()

student_id      0
student_name    0
age             0
sex             0
embarked        0
study_hours     0
total_marks     0
result          0
dtype: int64

In [9]:
df.dropna(inplace=True)

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['sex'] = le.fit_transform(df['sex'])

In [13]:
df.head()

,student_id,student_name,age,sex,embarked,study_hours,total_marks,result
0,101,Aarav Sharma,19.0,0,Hyderabad,5,72,Pass
1,102,Ananya Reddy,20.0,0,Vijayawada,7,88,Pass
2,103,Arjun Kumar,20.0,1,Hyderabad,3,38,Fail
3,104,Diya Patel,18.0,0,Visakhapatnam,6,81,Pass
4,105,Rohan Singh,21.0,1,Vijayawada,4,55,Pass

In [14]:
df = pd.get_dummies(
    df,
    columns=['embarked'],
    drop_first=True
)

In [15]:
drop_first=True

In [16]:
print(df.head())

print("\nDataset Shape:")
print(df.shape)

print("\nDataset Information:")
df.info()

   student_id  student_name   age  sex  study_hours  total_marks result  \
0         101  Aarav Sharma  19.0    0            5           72   Pass
1         102  Ananya Reddy  20.0    0            7           88   Pass
2         103   Arjun Kumar  20.0    1            3           38   Fail
3         104    Diya Patel  18.0    0            6           81   Pass
4         105   Rohan Singh  21.0    1            4           55   Pass

   embarked_Vijayawada  embarked_Visakhapatnam
0                False                   False
1                 True                   False
2                False                   False
3                False                    True
4                 True                   False

Dataset Shape:
(30, 9)

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              30 non-null     int64
 1   student_name            30 non-null     object
 2   age                     30 non-null     float64
 3   sex                     30 non-null     int64
 4   study_hours             30 non-null     int64
 5   total_marks             30 non-null     int64
 6   result                  30 non-null     object
 7   embarked_Vijayawada     30 non-null     bool
 8   embarked_Visakhapatnam  30 non-null     bool
dtypes: bool(2), float64(1), int64(4), object(2)
memory usage: 1.9+ KB

In [21]:
X = df[
    [
        'age',
        'sex',
        'study_hours',
        'total_marks'
    ]
]

y = df['result']

In [22]:
df['result'] = df['result'].map({
    'Fail': 0,
    'Pass': 1
})

In [23]:
y = df['result']

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)